NOTATION:

[] → optional (zero or one)
{} → zero or more
|  → alternative


GRAMMAR RULES
=================================================

program             = { statement } ;

statement           = var_decl
                    | assignment ;

var_decl            = type, IDENTIFIER, [ EQUAL, expression ], SEMI ;

assignment          = var_access, assignment_operator, expression, SEMI ;

expression          = primary ;

primary             = literal
                    | var_access ;

var_access          = IDENTIFIER ;

type                = INTEGER_TYPE ;

literal             = INTEGER_LITERAL ;

assignment_operator = EQUAL ;


TOKENS
=================================================

SEMI                = ";"

EQUAL               = "="

INTEGER_TYPE        = "int"

IDENTIFIER          = "[a-zA-z_][a-zA-Z0-9_]*"

INTEGER_LITERAL     = "[0-9]+"