#include <gtest/gtest.h>
#include "../SemanticTestUtils.h"

using namespace semanticTest;

TEST(EXPR_BINARY, ADD_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 + 5;");
}

TEST(EXPR_BINARY, ADD_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 + 5.5f;");
}

TEST(EXPR_BINARY, ADD_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 + 'a';");
}

TEST(EXPR_BINARY, ADD_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f + 5;");
}

TEST(EXPR_BINARY, ADD_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f + 5.5f;");
}

TEST(EXPR_BINARY, ADD_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f + 'a';");
}

TEST(EXPR_BINARY, ADD_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' + 1;");
}

TEST(EXPR_BINARY, ADD_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 'a' + 5.5f;");
}

TEST(EXPR_BINARY, ADD_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' + 'a';");
}

TEST(EXPR_BINARY, INVALID_ADD_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 + true;");
}

TEST(EXPR_BINARY, INVALID_ADD_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = 5.5f + true;");
}

TEST(EXPR_BINARY, INVALID_ADD_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true + 1;");
}

TEST(EXPR_BINARY, INVALID_ADD_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("float x = true + 5.5f;");
}

TEST(EXPR_BINARY, INVALID_ADD_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true + true;");
}

TEST(EXPR_BINARY, INVALID_ADD_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true + 'a';");
}

TEST(EXPR_BINARY, INVALID_ADD_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'a' + true;");
}

TEST(EXPR_BINARY, INVALID_ADD_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 + arr;
        )"
    );
}

TEST(EXPR_BINARY, SUBTRACT_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 - 5;");
}

TEST(EXPR_BINARY, SUBTRACT_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 - 5.5f;");
}

TEST(EXPR_BINARY, SUBTRACT_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 - 'a';");
}

TEST(EXPR_BINARY, SUBTRACT_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f - 5;");
}

TEST(EXPR_BINARY, SUBTRACT_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f - 5.5f;");
}

TEST(EXPR_BINARY, SUBTRACT_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f - 'a';");
}

TEST(EXPR_BINARY, SUBTRACT_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' - 1;");
}

TEST(EXPR_BINARY, SUBTRACT_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 'a' - 5.5f;");
}

TEST(EXPR_BINARY, SUBTRACT_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' - 'a';");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 - true;");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f - true;");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true - 1;");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true - 5.5f;");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true - false;");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true - 'a';");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'a' - true;");
}

TEST(EXPR_BINARY, INVALID_SUBTRACT_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 - arr;
        )"
    );
}

TEST(EXPR_BINARY, MULTIPLY_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 * 5;");
}

TEST(EXPR_BINARY, MULTIPLY_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 * 5.5f;");
}

TEST(EXPR_BINARY, MULTIPLY_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 1 * 'a';");
}

TEST(EXPR_BINARY, MULTIPLY_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f * 5;");
}

TEST(EXPR_BINARY, MULTIPLY_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f * 5.5f;");
}

TEST(EXPR_BINARY, MULTIPLY_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f * 'a';");
}

TEST(EXPR_BINARY, MULTIPLY_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' * 1;");
}

TEST(EXPR_BINARY, MULTIPLY_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 'a' * 5.5f;");
}

TEST(EXPR_BINARY, MULTIPLY_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' * 'a';");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 * true;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f * true;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true * 1;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true * 5.5f;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true * false;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true * 'a';");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'a' * false;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 * arr;
        )"
    );
}

TEST(EXPR_BINARY, DIVIDE_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 / 5;");
}

TEST(EXPR_BINARY, DIVIDE_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 / 5.5f;");
}

TEST(EXPR_BINARY, DIVIDE_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("float x = 1 / 'a';");
}

TEST(EXPR_BINARY, DIVIDE_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f / 5;");
}

TEST(EXPR_BINARY, DIVIDE_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f / 5.5f;");
}

TEST(EXPR_BINARY, DIVIDE_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f / 'a';");
}

TEST(EXPR_BINARY, DIVIDE_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 'a' / 1;");
}

TEST(EXPR_BINARY, DIVIDE_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 'a' / 5.5f;");
}

TEST(EXPR_BINARY, DIVIDE_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("float x = 'a' / 'a';");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = 1 / true;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = 5.5f / true;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("float x = true / 1;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("float x = true / 5.5f;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = true / true;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("float x = true / 'a';");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = 'a' / true;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 == arr;
        )"
    );
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 // 5;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 // 5.5f;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 1 // 'a';");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5.5f // 5;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5.5f // 5.5f;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5.5f // 'a';");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' // 1;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' // 5.5f;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' // 'a';");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 // true;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f / true;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true // 1;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true // 5.5f;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true // true;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true // 'a';");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'a' // true;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 // arr;
        )"
    );
}

TEST(EXPR_BINARY, MODULO_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 % 5;");
}

TEST(EXPR_BINARY, MODULO_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 % 5.5f;");
}

TEST(EXPR_BINARY, MODULO_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 1 % 'a';");
}

TEST(EXPR_BINARY, MODULO_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f % 5;");
}

TEST(EXPR_BINARY, MODULO_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f % 5.5f;");
}

TEST(EXPR_BINARY, MODULO_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f % 'a';");
}

TEST(EXPR_BINARY, MODULO_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' % 1;");
}

TEST(EXPR_BINARY, MODULO_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 'a' % 5.5f;");
}

TEST(EXPR_BINARY, MODULO_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'a' % 'a';");
}

TEST(EXPR_BINARY, INVALID_MODULO_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = 1 % true;");
}

TEST(EXPR_BINARY, INVALID_MODULO_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = 5.5f % true;");
}

TEST(EXPR_BINARY, INVALID_MODULO_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("float x = true % 1;");
}

TEST(EXPR_BINARY, INVALID_MODULO_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("float x = true % 5.5f;");
}

TEST(EXPR_BINARY, INVALID_MODULO_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = true % true;");
}

TEST(EXPR_BINARY, INVALID_MODULO_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("float x = true % 'a';");
}

TEST(EXPR_BINARY, INVALID_MODULO_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("float x = 'a' % true;");
}

TEST(EXPR_BINARY, INVALID_MODULO_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 % arr;
        )"
    );
}

TEST(EXPR_BINARY, BITWISE_AND_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 & 5;");
}

TEST(EXPR_BINARY, BITWISE_AND_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 & 'A';");
}

TEST(EXPR_BINARY, BITWISE_AND_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' & 5;");
}

TEST(EXPR_BINARY, BITWISE_AND_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' & 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 & 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 & true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f & 5;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f & 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f & true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f & 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true & 5;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true & 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true & true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true & 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' & 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' & true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_AND_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 & arr;
        )"
    );
}

TEST(EXPR_BINARY, BITWISE_OR_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 | 5;");
}

TEST(EXPR_BINARY, BITWISE_OR_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 | 'A';");
}

TEST(EXPR_BINARY, BITWISE_OR_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' | 5;");
}

TEST(EXPR_BINARY, BITWISE_OR_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' | 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 | 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 | true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f | 5;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f | 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f | true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f | 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true | 5;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true | 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true | true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true | 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' | 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' | true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_OR_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 | arr;
        )"
    );
}

TEST(EXPR_BINARY, BITWISE_XOR_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 ^ 5;");
}

TEST(EXPR_BINARY, BITWISE_XOR_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 ^ 'A';");
}

TEST(EXPR_BINARY, BITWISE_XOR_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' ^ 5;");
}

TEST(EXPR_BINARY, BITWISE_XOR_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' ^ 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 ^ 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 ^ true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f ^ 5;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f ^ 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f ^ true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f ^ 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true ^ 5;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true ^ 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true ^ true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true ^ 'A';");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' ^ 5.5f;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' ^ true;");
}

TEST(EXPR_BINARY, INVALID_BITWISE_XOR_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 ^ arr;
        )"
    );
}

TEST(EXPR_BINARY, LEFT_SHIFT_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 << 5;");
}

TEST(EXPR_BINARY, LEFT_SHIFT_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 << 'A';");
}

TEST(EXPR_BINARY, LEFT_SHIFT_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' << 5;");
}

TEST(EXPR_BINARY, LEFT_SHIFT_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' << 'A';");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 << 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 << true;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f << 5;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f << 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f << true;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f << 'A';");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true << 5;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true << 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true << true;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true << 'A';");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' << 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' << true;");
}

TEST(EXPR_BINARY, INVALID_LEFT_SHIFT_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 << arr;
        )"
    );
}

TEST(EXPR_BINARY, ARITHMETIC_RIGHT_SHIFT_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 >> 'A';");
}

TEST(EXPR_BINARY, ARITHMETIC_RIGHT_SHIFT_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' >> 5;");
}

TEST(EXPR_BINARY, ARITHMETIC_RIGHT_SHIFT_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' >> 'A';");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 >> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 >> true;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >> 5;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >> true;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >> 'A';");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >> 5;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >> true;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >> 'A';");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' >> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' >> true;");
}

TEST(EXPR_BINARY, INVALID_ARITHMETIC_RIGHT_SHIFT_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 >> arr;
        )"
    );
}

TEST(EXPR_BINARY, LOGICAL_RIGHT_SHIFT_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 >>> 'A';");
}

TEST(EXPR_BINARY, LOGICAL_RIGHT_SHIFT_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' >>> 5;");
}

TEST(EXPR_BINARY, LOGICAL_RIGHT_SHIFT_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("int x = 'A' >>> 'A';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 >>> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5 >>> true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >>> 5;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >>> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >>> true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = 5.5f >>> 'A';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >>> 5;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >>> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >>> true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("int x = true >>> 'A';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' >>> 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 'A' >>> true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_RIGHT_SHIFT_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 >>> arr;
        )"
    );
}

TEST(EXPR_BINARY, LOGICAL_OR_BOOL_BOOL) {
    ASSERT_SEMANTICALLY_VALID("bool x = true || true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_INT_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 || 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 || 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 || false;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_INT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 || 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f || 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f || 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f || false;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f || 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true || 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 || 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true || 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_CHAR_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' || 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' || 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' || false;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_CHAR_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' || 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 || arr;
        )"
    );
}

TEST(EXPR_BINARY, LOGICAL_AND_BOOL_BOOL) {
    ASSERT_SEMANTICALLY_VALID("bool x = true && false;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_INT_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 && 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_INT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 && 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 && false;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_INT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 && 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_FLOAT_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f && 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_FLOAT_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f && 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f && false;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_FLOAT_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f && 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true && 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 && 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true && 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_CHAR_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' && 1;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_CHAR_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' && 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' && false;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_CHAR_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' && 'a';");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 && arr;
        )"
    );
}

TEST(EXPR_BINARY, EQUAL_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 == 10;");
}

TEST(EXPR_BINARY, EQUAL_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 == 5.5f;");
}

TEST(EXPR_BINARY, EQUAL_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 == 'a';");
}

TEST(EXPR_BINARY, EQUAL_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f == 5;");
}

TEST(EXPR_BINARY, EQUAL_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f == 5.5f;");
}

TEST(EXPR_BINARY, EQUAL_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f == 'a';");
}

TEST(EXPR_BINARY, EQUAL_BOOL_BOOL) {
    ASSERT_SEMANTICALLY_VALID("bool x = true == true;");
}

TEST(EXPR_BINARY, EQUAL_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' == 1;");
}

TEST(EXPR_BINARY, INVALID_EQUAL_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' == 5.5f;");
}

TEST(EXPR_BINARY, EQUAL_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' == 'a';");
}

TEST(EXPR_BINARY, INVALID_EQUAL_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 == true;");
}

TEST(EXPR_BINARY, INVALID_EQUAL_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f == true;");
}

TEST(EXPR_BINARY, INVALID_EQUAL_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true == 'a';");
}

TEST(EXPR_BINARY, INVALID_EQUAL_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true == 'a';");
}

TEST(EXPR_BINARY, INVALID_EQUAL_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true == 'a';");
}

TEST(EXPR_BINARY, INVALID_EQUAL_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' == true;");
}

TEST(EXPR_BINARY, INVALID_EQUAL_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 == arr;
        )"
    );
}

TEST(EXPR_BINARY, NOT_EQUAL_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 != 10;");
}

TEST(EXPR_BINARY, NOT_EQUAL_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 != 5.5f;");
}

TEST(EXPR_BINARY, NOT_EQUAL_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 != 'a';");
}

TEST(EXPR_BINARY, NOT_EQUAL_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f != 5;");
}

TEST(EXPR_BINARY, NOT_EQUAL_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f != 5.5f;");
}

TEST(EXPR_BINARY, NOT_EQUAL_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f != 'a';");
}

TEST(EXPR_BINARY, NOT_EQUAL_BOOL_BOOL) {
    ASSERT_SEMANTICALLY_VALID("bool x = true != true;");
}

TEST(EXPR_BINARY, NOT_EQUAL_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' != 1;");
}

TEST(EXPR_BINARY, NOT_EQUAL_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' != 5.5f;");
}

TEST(EXPR_BINARY, NOT_EQUAL_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' != 'a';");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 != true;");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f != true;");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true != 'a';");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true != 'a';");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true != 'a';");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' != true;");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 != arr;
        )"
    );
}

TEST(EXPR_BINARY, LESS_THAN_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 < 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 < 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 < 'a';");
}

TEST(EXPR_BINARY, LESS_THAN_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f < 5;");
}

TEST(EXPR_BINARY, LESS_THAN_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f < 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f < 'a';");
}

TEST(EXPR_BINARY, LESS_THAN_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' < 5;");
}

TEST(EXPR_BINARY, LESS_THAN_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' < 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' < 'a';");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 < true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f < true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true < 1;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true < 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true < true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true < 'a';");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' < true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 < arr;
        )"
    );
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 <= 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 <= 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 <= 'a';");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f <= 5;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f <= 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f <= 'a';");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' <= 1;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' <= 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_TO_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' <= 'a';");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 <= true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f <= true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true <= 1;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true <= 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true <= true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true <= 'a';");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' <= true;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 <= arr;
        )"
    );
}

TEST(EXPR_BINARY, GREATER_THAN_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 > 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 > 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 > 'a';");
}

TEST(EXPR_BINARY, GREATER_THAN_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f > 5;");
}

TEST(EXPR_BINARY, GREATER_THAN_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f > 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f > 'a';");
}

TEST(EXPR_BINARY, GREATER_THAN_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' > 1;");
}

TEST(EXPR_BINARY, GREATER_THAN_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' > 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' > 'a';");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 > true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f > true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true > 1;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true > 5.5f;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true > true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true > 'a';");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' > true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 > arr;
        )"
    );
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 >= 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 >= 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_INT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 >= 'a';");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f >= 5;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f >= 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_FLOAT_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f >= 'a';");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_CHAR_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' >= 1;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_CHAR_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' >= 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_TO_CHAR_CHAR) {
    ASSERT_SEMANTICALLY_VALID("bool x = 'a' >= 'a';");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 1 >= true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f >= true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true >= 1;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true >= 5.5f;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_BOOL_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true >= true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_BOOL_CHAR) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true >= 'a';");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_CHAR_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 'a' >= true;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_INT_ARRAY) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] arr = new int[3];
            bool x = 1 >= arr;
        )"
    );
}
