#include <gtest/gtest.h>
#include "../SemanticTestUtils.h"

using namespace semanticTest;

TEST(EXPR_BINARY, PLUS_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 + 5;");
}

TEST(EXPR_BINARY, PLUS_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 + 5.5f;");
}

TEST(EXPR_BINARY, PLUS_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f + 5;");
}

TEST(EXPR_BINARY, PLUS_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f + 5.5f;");
}

TEST(EXPR_BINARY, MINUS_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 - 5;");
}

TEST(EXPR_BINARY, MINUS_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 - 5.5f;");
}

TEST(EXPR_BINARY, MINUS_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f - 5;");
}

TEST(EXPR_BINARY, MINUS_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f - 5.5f;");
}

TEST(EXPR_BINARY, MULTIPLY_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 * 5;");
}

TEST(EXPR_BINARY, MULTIPLY_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 * 5.5f;");
}

TEST(EXPR_BINARY, MULTIPLY_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f * 5;");
}

TEST(EXPR_BINARY, MULTIPLY_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f * 5.5f;");
}

TEST(EXPR_BINARY, DIVIDE_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 / 5;");
}

TEST(EXPR_BINARY, DIVIDE_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 / 5.5f;");
}

TEST(EXPR_BINARY, DIVIDE_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f / 5;");
}

TEST(EXPR_BINARY, DIVIDE_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f / 5.5f;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 // 5;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 // 5.5f;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5.5f // 5;");
}

TEST(EXPR_BINARY, INTEGER_DIVIDE_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5.5f // 5.5f;");
}

TEST(EXPR_BINARY, MODULO_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("int x = 5 % 5;");
}

TEST(EXPR_BINARY, MODULO_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f % 5;");
}

TEST(EXPR_BINARY, MODULO_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5 % 5.5f;");
}

TEST(EXPR_BINARY, MODULO_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("float x = 5.5f % 5.5f;");
}

TEST(EXPR_BINARY, LOGICAL_OR_BOOL) {
    ASSERT_SEMANTICALLY_VALID("bool x = true || true;");
}

TEST(EXPR_BINARY, LOGICAL_AND_BOOL) {
    ASSERT_SEMANTICALLY_VALID("bool x = true && false;");
}

TEST(EXPR_BINARY, EQUAL_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 == 10;");
}

TEST(EXPR_BINARY, EQUAL_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 == 5.5f;");
}

TEST(EXPR_BINARY, EQUAL_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f == 5;");
}

TEST(EXPR_BINARY, EQUAL_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f == 5.5f;");
}

TEST(EXPR_BINARY, NOT_EQUAL_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 != 10;");
}

TEST(EXPR_BINARY, NOT_EQUAL_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 != 5.5f;");
}

TEST(EXPR_BINARY, NOT_EQUAL_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f != 5;");
}

TEST(EXPR_BINARY, NOT_EQUAL_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f != 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 < 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 < 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f < 5;");
}

TEST(EXPR_BINARY, LESS_THAN_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f < 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 <= 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 <= 5.5f;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f <= 5;");
}

TEST(EXPR_BINARY, LESS_THAN_OR_EQUAL_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f <= 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 > 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 > 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f > 5;");
}

TEST(EXPR_BINARY, GREATER_THAN_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f > 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_INT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 >= 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_INT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5 >= 5.5f;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_FLOAT_INT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f >= 5;");
}

TEST(EXPR_BINARY, GREATER_THAN_OR_EQUAL_FLOAT_FLOAT) {
    ASSERT_SEMANTICALLY_VALID("bool x = 5.5f >= 5.5f;");
}

TEST(EXPR_BINARY, INVALID_PLUS_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true + 1;");
}

TEST(EXPR_BINARY, INVALID_PLUS_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 + true;");
}

TEST(EXPR_BINARY, INVALID_MINUS_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true - 1;");
}

TEST(EXPR_BINARY, INVALID_MINUS_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 - true;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true * 1;");
}

TEST(EXPR_BINARY, INVALID_MULTIPLY_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 * true;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true / 1;");
}

TEST(EXPR_BINARY, INVALID_DIVIDE_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 / true;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true // 1;");
}

TEST(EXPR_BINARY, INVALID_INTEGER_DIVIDE_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 // true;");
}

TEST(EXPR_BINARY, INVALID_MODULO_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("int x = true % 1;");
}

TEST(EXPR_BINARY, INVALID_MODULO_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("int x = 1 % true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5 || true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true || 5;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f || true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_OR_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true || 5.5f;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5 && true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true && 5;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_FLOAT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 5.5f && true;");
}

TEST(EXPR_BINARY, INVALID_LOGICAL_AND_BOOL_FLOAT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = true && 5.5f;");
}

TEST(EXPR_BINARY, INVALID_EQUAL_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = false == 10;");
}

TEST(EXPR_BINARY, INVALID_EQUAL_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 10 == false;");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = false != 10;");
}

TEST(EXPR_BINARY, INVALID_NOT_EQUAL_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 10 != false;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = false < 10;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 10 < false;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = false <= 10;");
}

TEST(EXPR_BINARY, INVALID_LESS_THAN_OR_EQUAL_TO_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 10 <= false;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = false > 10;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 10 > false;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_BOOL_INT) {
    ASSERT_THROWS_TYPE_ERROR("bool x = false >= 10;");
}

TEST(EXPR_BINARY, INVALID_GREATER_THAN_OR_EQUAL_TO_INT_BOOL) {
    ASSERT_THROWS_TYPE_ERROR("bool x = 10 >= false;");
}
