#include <gtest/gtest.h>
#include "../SemanticTestUtils.h"

using namespace semanticTest;

TEST(EXPR_NEW, ONE_DIMENSIONAL_INT_ARRAY) {
    ASSERT_SEMANTICALLY_VALID("int[] x = new int[3];");
}

TEST(EXPR_NEW, ONE_DIMENSIONAL_INT_ARRAY_WITH_INITIALISER_NO_VALUES) {
    ASSERT_SEMANTICALLY_VALID("int[] x = new int[3]{};");
}

TEST(EXPR_NEW, ONE_DIMENSIONAL_INT_ARRAY_WITH_INITIALISER_WITH_VALUES) {
    ASSERT_SEMANTICALLY_VALID("int[] x = new int[3]{1, 2, 3};");
}

TEST(EXPR_NEW, ONE_DIMENSIONAL_FLOAT_ARRAY) {
    ASSERT_SEMANTICALLY_VALID("float[] x = new float[3];");
}

TEST(EXPR_NEW, ONE_DIMENSIONAL_FLOAT_ARRAY_WITH_INITIALISER_WITH_VALUES) {
    ASSERT_SEMANTICALLY_VALID("float[] x = new float[3]{1.0f, 2.0f, 3.0f};");
}

TEST(EXPR_NEW, ONE_DIMENSIONAL_FLOAT_ARRAY_WITH_INITIALISER_WITH_INT_VALUES) {
    ASSERT_SEMANTICALLY_VALID("float[] x = new float[3]{1, 2, 3};");
}

TEST(EXPR_NEW, ONE_DIMENSIONAL_BOOL_ARRAY) {
    ASSERT_SEMANTICALLY_VALID("bool[] x = new bool[3];");
}

TEST(EXPR_NEW, ONE_DIMENSIONAL_BOOL_ARRAY_WITH_INITIALISER_WITH_VALUES) {
    ASSERT_SEMANTICALLY_VALID("bool[] x = new bool[3]{true, false};");
}

TEST(EXPR_NEW, TWO_DIMENSIONAL_INT_ARRAY) {
    ASSERT_SEMANTICALLY_VALID("int[][] x = new int[3][3];");
}

TEST(EXPR_NEW, TWO_DIMENSIONAL_INT_ARRAY_WITH_INITIALISER_NO_VALUES) {
    ASSERT_SEMANTICALLY_VALID("int[][] x = new int[3][3]{};");
}

TEST(EXPR_NEW, TWO_DIMENSIONAL_INT_ARRAY_WITH_INITIALISER_WITH_VALUES) {
    ASSERT_SEMANTICALLY_VALID("int[][] x = new int[3][3]{{1},{1, 2}};");
}

TEST(EXPR_NEW, TWO_DIMENSIONAL_FLOAT_ARRAY) {
    ASSERT_SEMANTICALLY_VALID("float[][] x = new float[3][3];");
}

TEST(EXPR_NEW, TWO_DIMENSIONAL_FLOAT_ARRAY_WITH_INITIALISER_WITH_VALUES) {
    ASSERT_SEMANTICALLY_VALID("float[][] x = new float[3][3]{{1.0f},{1.0f, 2.0f}};");
}

TEST(EXPR_NEW, TWO_DIMENSIONAL_BOOL_ARRAY) {
    ASSERT_SEMANTICALLY_VALID("bool[][] x = new bool[3][3];");
}

TEST(EXPR_NEW, TWO_DIMENSIONAL_BOOL_ARRAY_WITH_INITIALISER_WITH_VALUES) {
    ASSERT_SEMANTICALLY_VALID("bool[][] x = new bool[3][3]{{true},{false, true}, {}};");
}

TEST(EXPR_NEW, INVALID_FLOAT_ARRAY_DIMENSION) {
    ASSERT_THROWS_TYPE_ERROR("int[] x = new int[5.5f];");
}

TEST(EXPR_NEW, INVALID_BOOL_ARRAY_DIMENSION) {
    ASSERT_THROWS_TYPE_ERROR("int[] x = new int[false];");
}

TEST(EXPR_NEW, INVALID_INT_ARRAY_ARRAY_DIMENSION) {
    ASSERT_THROWS_TYPE_ERROR(
        R"(
            int[] x = new int[1];
            int[] arr = new int[x];
        )"
    );
}

TEST(EXPR_NEW, INVALID_INT_ARRAY_WITH_BOOL_INITIALISER) {
    ASSERT_THROWS_TYPE_ERROR("int[] x = new int[3]{true, false};");
}

TEST(EXPR_NEW, INVALID_BOOL_ARRAY_WITH_FLOAT_INITIALISER) {
    ASSERT_THROWS_TYPE_ERROR("bool[][] x = new bool[3][3]{1.0f, 2.0f};");
}

TEST(EXPR_NEW, INVALID_INT_ARRAY_WITH_FLOAT_INITIALISER) {
    ASSERT_THROWS_TYPE_ERROR("int[][] x = new int[3][3]{1.0f, 2.0f};");
}

TEST(EXPR_NEW, INVALID_INT_ARRAY_WITH_INITIALISER_TOO_SHALLOW) {
    ASSERT_THROWS_TYPE_ERROR("int[][] x = new int[3][3]{1, 2};");
}

TEST(EXPR_NEW, INVALID_INT_ARRAY_WITH_INITIALISER_TOO_DEEP) {
    ASSERT_THROWS_TYPE_ERROR("int[] x = new int[3][3]{{1, 2}, 2};");
}

