#include <gtest/gtest.h>
#include "TokeniserTestUtils.h"

using namespace tokeniserTest;

TEST(IDENTIFIER, ONE_CHAR) {
    ASSERT_TOKEN_EQ("x", TokenKind::IDENTIFIER, "x");
}

TEST(IDENTIFIER, ONE_CHAR_CAPITALISED) {
    ASSERT_TOKEN_EQ("X", TokenKind::IDENTIFIER, "X");
}

TEST(IDENTIFIER, ONE_CHAR_UNDERSCORE) {
    ASSERT_TOKEN_EQ("_", TokenKind::IDENTIFIER, "_");
}

TEST(IDENTIFIER, MULTI_CHAR) {
    ASSERT_TOKEN_EQ("abc", TokenKind::IDENTIFIER, "abc");
}

TEST(IDENTIFIER, MULTI_IWTH_UNDERSCORE) {
    ASSERT_TOKEN_EQ("Ab___c", TokenKind::IDENTIFIER, "Ab___c");
}

TEST(IDENTIFIER, MULTI_CHAR_WITH_DIGITS) {
    ASSERT_TOKEN_EQ("a1b2c3", TokenKind::IDENTIFIER, "a1b2c3");
}

TEST(IDENTIFIER, START_WITH_UNDERSCORE) {
    ASSERT_TOKEN_EQ("_x", TokenKind::IDENTIFIER, "_x");
}

TEST(IDENTIFIER, CONTAINS_KEYWORD) {
    ASSERT_TOKEN_EQ("returnV", TokenKind::IDENTIFIER, "returnV");
}

TEST(IDENTIFIER, INVALID_STARTS_WITH_DOUBLE_UNDERSCORE) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("__x");
}

TEST(IDENTIFIER, INVALID_STARTS_WITH_DIGIT) {
    ASSERT_FIRST_TOKEN_IS_NOT_IDENTIFIER("1var");
}