#include <gtest/gtest.h>
#include "TokeniserTestUtils.h"

using namespace tokeniserTest;

TEST(INVALID, DOUBLE_QUOTES) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("\"");
}

TEST(INVALID, HASH) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("#");
}

TEST(INVALID, DOLLAR) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("$");
}

TEST(INVALID, AMPERSAND) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("&");
}

TEST(INVALID, SINGLE_QUOTE) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("'");
}

TEST(INVALID, DOT) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR(".");
}

TEST(INVALID, COLON) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR(":");
}

TEST(INVALID, QUESTION_MARK) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("?");
}

TEST(INVALID, AT_SIGN) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("@");
}

TEST(INVALID, LSQBR) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("[");
}

TEST(INVALID, BACKSLASH) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("\\");
}

TEST(INVALID, RSQBR) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("]");
}

TEST(INVALID, CARET) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("^");
}

TEST(INVALID, GRAVE_ACCENT) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("`");
}

TEST(INVALID, VERTICAL_BAR) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("|");
}

TEST(INVALID, TILDE) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("~");
}

TEST(INVALID, POUND_SIGN) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("£");
}