#include <gtest/gtest.h>
#include "TokeniserTestUtils.h"

using namespace tokeniserTest;

TEST(LITERAL, INT_ONE_DIGIT) {
    ASSERT_TOKEN_EQ("0", TokenKind::INT_LITERAL, "0");
}

TEST(LITERAL, INT_MULTI_DIGI) {
    ASSERT_TOKEN_EQ("123", TokenKind::INT_LITERAL, "123");
}

TEST(LITERAL, FLOAT) {
    ASSERT_TOKEN_EQ("0.0f", TokenKind::FLOAT_LITERAL, "0.0");
}

TEST(LITERAL, FLOAT_MULTI_DIGIT_INTEGER_PART) {
    ASSERT_TOKEN_EQ("123.5f", TokenKind::FLOAT_LITERAL, "123.5");
}

TEST(LITERAL, FLOAT_MULTI_DIGIT_DECIMAL_PART) {
    ASSERT_TOKEN_EQ("5.123f", TokenKind::FLOAT_LITERAL, "5.123");
}

TEST(LITERAL, TRUE) {
    ASSERT_TOKEN_EQ("true", TokenKind::BOOL_LITERAL, "true");
}

TEST(LITERAL, FALSE) {
    ASSERT_TOKEN_EQ("false", TokenKind::BOOL_LITERAL, "false");
}

TEST(LITERAL, CHAR) {
    ASSERT_TOKEN_EQ("'a'", TokenKind::CHAR_LITERAL, "'a'");
}

TEST(LITERAL, CHAR_UTF_8) {
    ASSERT_TOKEN_EQ("'😀'", TokenKind::CHAR_LITERAL, "'😀'");
}

TEST(LITERAL, ESCAPE_SEQUENCE) {
    ASSERT_TOKEN_EQ("'\\n'", TokenKind::CHAR_LITERAL, "'\\n'");
}

TEST(LITERAL, INVALID_FLOAT_MISSING_F_CAHR) {
    ASSERT_TOKEN_THROWS_SYNTAX_ERROR("5.5");
}

TEST(LITERAL, INVALID_FLOAT_MISSING_DECIMAL_PART) {
    ASSERT_TOKEN_THROWS_SYNTAX_ERROR("5.f");
}

TEST(LITERAL, INVALID_CHAR_MISSING_CLOSING_QUOTE) {
    ASSERT_TOKEN_THROWS_SYNTAX_ERROR("'a");
}

TEST(LITERAL, INVALID_CHAR_EMPTY) {
    ASSERT_TOKEN_THROWS_SYNTAX_ERROR("''");
}

TEST(LITERAL, INVALID_MULTIPLE_CHARS) {
    ASSERT_TOKEN_THROWS_SYNTAX_ERROR("'ab'");
}

TEST(LITERAL, INVALID_ESCAPE_SEQUENCE) {
    ASSERT_TOKEN_THROWS_SYNTAX_ERROR("'\\a'");
}
