#include <gtest/gtest.h>
#include "tokeniserTestUtils.h"

using namespace tokeniserTest;

TEST(LITERAL, INT_ONE_DIGIT) {
    ASSERT_TOKEN_EQ("0", TokenKind::INTEGER_LITERAL, "0");
}

TEST(LITERAL, INT_MULTI_DIGI) {
    ASSERT_TOKEN_EQ("123", TokenKind::INTEGER_LITERAL, "123");
}

TEST(LITERAL, FLOAT) {
    ASSERT_TOKEN_EQ("0.0f", TokenKind::FLOAT_LITERAL, "0.0");
}

TEST(LITERAL, FLOAT_MULTI_DIGIT_INTEGER_PART) {
    ASSERT_TOKEN_EQ("123.5f", TokenKind::FLOAT_LITERAL, "123.5");
}

TEST(LITERAL, FLOAT_MULTI_DIGIT_DECIMAL_PART) {
    ASSERT_TOKEN_EQ("5.123f", TokenKind::FLOAT_LITERAL, "5.123");
}

TEST(LITERAL, TRUE) {
    ASSERT_TOKEN_EQ("true", TokenKind::BOOL_LITERAL, "true");
}

TEST(LITERAL, FALSE) {
    ASSERT_TOKEN_EQ("false", TokenKind::BOOL_LITERAL, "false");
}

TEST(LITERAL, INVALID_FLOAT_MISSING_F_CAHR) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("5.5");
}

TEST(LITERAL, INVALID_FLOAT_MISSING_DECIMAL_PART) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR("5.f");
}

TEST(LITERAL, INVALID_FLOAT_MISSING_INTEGER_PART) {
    ASSERT_TOKEN_THROWS_LEXICAL_ERROR(".5f");
}
