#include "Driver.h"
#include "assembler/Assembler.h"
#include "vm/VM.h"

#include <iostream>
#include <filesystem>
#include <fstream>

#include "compiler/Compiler.h"


int Driver::runCLI(int argc, char* argv[]) {
    if (argc < 2) {
        std::cerr << "Error: no command provided.'\n";
        return 1;
    }

    const std::string command = argv[1];

    if (command == "run") {
        if (argc < 3) {
            std::cerr << "Error: no file path provided'\n";
            return 1;
        }
        return run(argv[2]);
    }

    if (command == "compile") {
        if (argc < 3) {
            std::cerr << "Error: no file path provided'\n";
            return 1;
        }
        return compile(argv[2]);
    }

    if (command == "assemble") {
        if (argc < 3) {
            std::cerr << "Error: no file path provided'\n";
            return 1;
        }
        return assemble(argv[2]);
    }

    if (command == "execute") {
        if (argc < 3) {
            std::cerr << "Error: no file path provided'\n";
            return 1;
        }
        return execute(argv[2]);
    }

    std::cerr << "Unknown command: " << command << std::endl;

    return 1;
}

int Driver::run(const char* filePath) {
    if (!isValidFileExtension(filePath, &PROGRAMMING_LANGUAGE_FILE_EXTENSION)) {
        return 1;
    }

    // compile code
    const auto* compiler = new compiler::Compiler();
    compiler->compile(filePath);
    delete compiler;

    // get fileName of generated assembly
    std::filesystem::path assemblyFilePath(filePath);
    assemblyFilePath.replace_extension(ASSEMBLY_FILE_EXTENSION);

    int exitCode;

    // assemble bytecode from assembly
    exitCode = assemble(assemblyFilePath.string().c_str());
    if (exitCode != 0) {
        return exitCode;
    }

    // get fileName of generated bytecode
    std::filesystem::path bytecodeFilePath(filePath);
    bytecodeFilePath.replace_extension(BYTECODE_FILE_EXTENSION);

    // execute bytecode
    exitCode = execute(bytecodeFilePath.string().c_str());
    if (exitCode != 0) {
        return exitCode;
    }

    return 0;
}

int Driver::compile(const char* filePath) {
    if (!isValidFileExtension(filePath, &PROGRAMMING_LANGUAGE_FILE_EXTENSION)) {
        return 1;
    }

    const auto* compiler = new compiler::Compiler();
    compiler->compile(filePath);
    delete compiler;

    return 0;
}

int Driver::assemble(const char* filePath) {
    if (!isValidFileExtension(filePath, &ASSEMBLY_FILE_EXTENSION)) {
        return 1;
    }

    const auto assembler = new assembler::Assembler();

    // assemble bytecode assembly
    const auto bytecode = assembler->assemble(std::string(filePath));

    delete assembler;

    if (!bytecode.has_value()) {
        return 1;
    }

    // replace .svma extension with .svmb
    std::filesystem::path outputFilePath(filePath);
    outputFilePath.replace_extension(BYTECODE_FILE_EXTENSION);

    // generate output file from bytecode stored in vector
    std::ofstream outputFile(outputFilePath);
    if (!outputFile.is_open()) {
        std::cerr << "Error: could not create and open " << outputFilePath << std::endl;
        return 1;
    }

    outputFile.write(
        reinterpret_cast<const char*>(bytecode->data()),
        static_cast<std::streamsize>(bytecode->size())
    );

    outputFile << std::dec << "\n";
    outputFile.close();
    return 0;
}

int Driver::execute(const char* filePath) {
    if (!isValidFileExtension(filePath, &BYTECODE_FILE_EXTENSION)) {
        return 1;
    }

    std::ifstream inputFile(filePath);
    if (!inputFile.is_open()) {
        std::cerr << "Error: could not open " << filePath << std::endl;
        return 1;
    }

    // read bytecode from file
    const std::vector<uint8_t> bytecode(
        (std::istreambuf_iterator<char>(inputFile)),
        std::istreambuf_iterator<char>()
    );

    // execute bytecode
    auto vm = new VM();
    vm->run(&bytecode);
    delete vm;

    return 0;
}

bool Driver::isValidFileExtension(const std::filesystem::path &filePath, const std::string_view* extension) {
    // validate file extension
    const std::filesystem::path path(filePath);
    if (path.extension() != *extension) {
        handleUnsupportedFileExtensionError(&path);
        return false;
    }
    return true;
}


void Driver::handleUnsupportedFileExtensionError(const std::filesystem::path* path) {
    std::cerr << "File extension \'"<< path->extension() << "\' is not supported" << std::endl;
}
