NOTATION:

[] → optional (zero or one)
{} → zero or more
|  → alternative


GRAMMAR RULES
=================================================

program                     = { statement | function_decl } ;

function_decl               = ( type | VOID_TYPE ), IDENTIFIER, LBR, [ parameter_list ], RBR, block ;

parameter_list              = parameter, { COMMA, parameter } ;

parameter                   = type, IDENTIFIER ;

statement                   = block
                            | var_decl
                            | assignment
                            | if_statement
                            | while_statement
                            | continue_statement
                            | break_statement
                            | function_call_statement
                            | return_statement ;

block                       = LCBR, { statement }, RCBR ;

var_decl                    = type, IDENTIFIER, [ EQUAL, expression ], SEMI ;

assignment                  = var_access, assignment_operator, expression, SEMI ;

if_statement                = IF, LBR, expression, RBR, block, [ ELSE, ( block | if_statement ) ] ;

while_statement             = WHILE, LBR, expression, RBR, block ;

continue_statement          = CONTINUE, SEMI ;

break_statement             = BREAK, SEMI ;

function_call_statement    = function_call, SEMI ;

return_statement            = RETURN, [ expression ], SEMI ;

expression                  = logical_or_expression ;

logical_or_expression       = logical_and_expression, { LOGICAL_OR, logical_and_expression } ;

logical_and_expression      = equality_expression, { LOGICAL_AND, equality_expression } ;

equality_expression         = comparison_expression, { ( EQUAL_EQUAL | NOT_EQUAL ), comparison_expression } ;

comparison_expression       = additive_expression, { ( LESS_THAN | LESS_THAN_OR_EQUAL | GREATER_THAN | GREATER_THAN_OR_EQUAL ), additive_expression } ;

additive_expression         = multiplicative_expression, { ( PLUS | MINUS ), multiplicative_expression } ;

multiplicative_expression   = unary_expression, { ( MULTIPLY | DIVIDE | INTEGER_DIVIDE | MODULO ), unary_expression } ;

unary_expression            = ( PLUS | MINUS | LOGICAL_NOT ), unary_expression
                            | LBR, type, RBR, unary_expression
                            | primary_expression ;

primary_expression          = function_call
                            | var_access
                            | literal
                            | LBR, expression, RBR ;

function_call               = IDENTIFIER, LBR, [ argument_list ], RBR ;

argument_list               = expression, { COMMA, expression } ;

var_access                  = IDENTIFIER ;

type                        = INTEGER_TYPE
                            | FLOAT_TYPE
                            | BOOL_TYPE ;

literal                     = INTEGER_LITERAL
                            | FLOAT_LITERAL
                            | BOOL_LITERAL ;

assignment_operator         = EQUAL ;


TOKENS
=================================================

SEMI                        = ";"
COMMA                       = ","
LBR                         = "("
RBR                         = ")"
LCBR                        = "{"
RCBR                        = "}"

EQUAL                       = "="
PLUS                        = "+"
MINUS                       = "-"
MULTIPLY                    = "*"
DIVIDE                      = "/"
INTEGER_DIVIDE              = "//"
MODULO                      = "%"

LOGICAL_OR                  = "||"
LOGICAL_AND                 = "&&"
LOGICAL_NOT                 = "!"
EQUAL_EQUAL                 = "=="
NOT_EQUAL                   = "!="
LESS_THAN                   = "<"
LESS_THAN_OR_EQUAL          = "<="
GREATER_THAN                = ">"
GREATER_THAN_OR_EQUAL       = ">="

IF                          = "if"
ELSE                        = "else"
WHILE                       = "while"
CONTINUE                    = "continue"
BREAK                       = "break"
RETURN                      = "return"

INTEGER_TYPE                = "int"
FLOAT_TYPE                  = "float"
BOOL_TYPE                   = "bool"
VOID_TYPE                   = "void"

INTEGER_LITERAL             = "[0-9]+"
FLOAT_LITERAL               = "[0-9]+\.[0-9]+f"
BOOL_LITERAL                = "true|false"

IDENTIFIER                  = "(?!__)[a-zA-Z_][a-zA-Z0-9_]*"